# PRODUCTION-ONLY: This config is for Cloudflare CI/CD deploys only.
# All bindings and variables must be present here.

name = "rhythm90-api"
main = "src/backend/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "rhythm90-db"
database_id = "73d8857c-97f9-4cfa-800a-225d7346be67"
migrations_dir = "migrations"

[vars]
APP_URL = "https://rhythm90.io"
ENVIRONMENT = "production"
MAILERSEND_FROM_EMAIL = "noreply@rhythm90.io"
MAILERSEND_FROM_NAME = "Rhythm90 Team" 