# WARNING: Deploying with wrangler will overwrite any environment variables and bindings set in the Cloudflare dashboard
# unless you use the --keep-vars flag. Always keep all required variables and bindings in this file.
# If you add variables/bindings in the dashboard, add them here as well to avoid losing them on deploy.

name = "rhythm90-real"
main = "src/backend/index.ts"
compatibility_date = "2024-01-15"

# Development environment
[env.development]
name = "rhythm90-real-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "rhythm90-db"
database_id = "73d8857c-97f9-4cfa-800a-225d7346be67"

[env.development.vars]
APP_URL = "http://localhost:5173"
ENVIRONMENT = "development"

# Production environment
[env.production]
name = "rhythm90-api"

[[env.production.d1_databases]]
binding = "DB"
database_name = "rhythm90-db"
database_id = "73d8857c-97f9-4cfa-800a-225d7346be67"

# Production environment variables (APP_URL, ENVIRONMENT) are managed in the Cloudflare dashboard, not here. 