name = "rhythm90-real"
main = "src/backend/index.ts"
compatibility_date = "2024-01-15"

[env.production]
name = "rhythm90-real"

[[env.production.d1_databases]]
binding = "DB"
database_name = "rhythm90-db"
database_id = "73d8857c-97f9-4cfa-800a-225d7346be67"

[env.production.vars]
APP_URL = "https://rhythm90-real.pages.dev" 